type Query {
  draggedCardId: ID
  draggedListId: ID
  overlaidCardId: ID
  controlVariable: ControlType
}

type CardAddInitiated {
  listId: ID!
  inputText: String!
}

type CardDragged {
  listId: ID!
  cardId: ID!
}

type CardDraggedOverCard {
  listId: ID!
  cardId: ID!
  overlaidCardId: ID
}

type ListDragged {
  listId: ID!
  overlaidListId: ID
}

type CardDetailOpened {
  cardId: ID!
}

union ControlType =
    CardAddInitiated
  | CardDragged
  | CardDraggedOverCard
  | ListDragged
  | CardDetailOpened
