type Query {
  draggedCardId: ID
  draggedListId: ID
  overlaidCardId: ID
  editScreenCardId: ID
  cartItems: [Int]
  cardAdding: CardAdding
  controlVariable: ControlType
}

type CardAdding {
  listId: ID
  inputText: String
}

type CardAddInitiated {
  listId: ID!
  inputText: String!
}

type CardDragged {
  listId: ID!
  cardId: ID!
  overlaidCardId: ID
}

type ListDragged {
  listId: ID!
}

type CardDetailOpened {
  cardId: ID!
}

union ControlType =
    CardAddInitiated
  | CardDragged
  | ListDragged
  | CardDetailOpened
