type Query {
  lists: [List]
  card(id: ID!): Card
}

type List {
  id: ID!
  title: String
  maxNumCards: Int
  cards: [Card]
}

type Card {
  id: ID!
  title: String
  description: String
  labels: [String]
}

type Mutation {
  addCardToList(listId: ID!, card: CardInput!): Int
  swapCardsWithinList(listId: ID!, card1Id: ID!, card2Id: ID!): Int
  swapCardsBetweenLists(
    list1Id: ID!
    list2Id: ID!
    card1Id: ID!
    card2Id: ID!
  ): Int
  swapLists(list1Id: ID!, list2Id: ID!): Int
}

input CardInput {
  title: String
  description: String
}
