type Query {
  hello: String
  search(department: String): [Employee]
}

type Employee {
  name: String
  jobTitle: String
  department: String
}

type Mutation {
  moveCardToList(
    fromListId: String
    toListId: String
    cardId: String
    listPositionIndex: String
  ): String
}
