type Query {
  lists: [List]
}

type List {
  id: ID!
  title: String
  maxNumCards: Int
  cards: [Card]
}

type Card {
  id: ID!
  title: String
  description: String
  labels: [String]
}

type Mutation {
  insertCardToList(atIndex: Int, listId: ID, cardId: ID): Int
  addCardToList(listId: ID, card: CardInput): Int
}

input CardInput {
  title: String
  description: String
}
