// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	ID          string    `json:"id"`
	Title       *string   `json:"title"`
	Description *string   `json:"description"`
	Labels      []*string `json:"labels"`
}

type CardInput struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
}

type List struct {
	ID          string  `json:"id"`
	Title       *string `json:"title"`
	MaxNumCards *int    `json:"maxNumCards"`
	Cards       []*Card `json:"cards"`
}
